version: "3.9"
services:
  backend:
    build: ./backend
    container_name: sentrius-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - sentrius_tmp:/tmp/sentrius
    depends_on:
      - frontend
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: sentrius-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE=http://localhost:8000
    volumes:
      - ./frontend:/app
    restart: unless-stopped

volumes:
  sentrius_tmp:
